### PR TITLE
Added fix for running Slimer (or potential other .bat engine files) u…

### PR DESCRIPTION
**Pull request by MaarekElets**
While working with https://github.com/nodeca/navit and implementing slimerjs into a scraping app, I discovered that under Windows when the slimerjs engine is loaded with the bridge,js script that the path to the bridge.js script has inconsistant slashes (the path from the require call returns a path like "c:\path\to\node-phantom-simple" while the appended bridge.js is added with "/bridge.js"). Under phantom.js (which is an .exe file) this does not appear to be a problem but when running as a batch file like slimerjs does under Windows it will fail to locate bridge.js. This PR resolves this by testing for options.phantomPath that ends in .bat and appending the bridge.js with consistent slashes.

I cannot run expresso for tests as I'm on Windows and expresso won't install or build from source (even under a Bash shell on Windows).

### CODE REVIEW

**Comment by puzrin** [comment]
IMHO it would be better to fix the source of wrong path content, instead of hacking it.

**Comment by puzrin** [comment]
Ah, looked again. Why not use `path.join` to get correct path in any OS without additional checks?

**Comment by MaarekElets** [comment]
That would be due to my relative inexperience with Node. Was unaware that path.join normalized in that way. I do think that would be better than a conditional test like I have. Would you like me to revise and resubmit or would you prefer to do it?

**Comment by puzrin** [comment]
Yes, if `path.joins(__dirname, bridge.js)` will fix your problem, please resubmit. With more clear/short text, something like `Fix path separators for Win, needed to run Slimer`.

**Comment by MaarekElets** [comment]
It's been updated and tested to the best of my abilities. Please forgive the excess commit.

**Comment by puzrin** [comment]
@MaarekElets I've just received collaborator perms to mainstream. If you have no objection, we will fix it directly in mainstream with other pending issues, and this repo will be finally killed.

**Comment by MaarekElets** [comment]
That's fine with me, only thing I care about is having it fixed! It was a good exercise for me anyway.

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple/commit/1dff63d3d2cb2f9ce3ba612d8eb0136b337d015c

**Pull request closed without merging**
